### PR TITLE
pin versions

### PR DESCRIPTION
**Pull request by jcrben**
I'm working with @simonmichael to run this over in #hledger at freenode but we've run into a couple hiccups. It seems plaid-python is shipping lots of updates lately https://pypi.org/project/plaid-python/#history - pinning to prevent any breakage.

I think  you'll need to cut a new release and update setup.py also, but not sure about those details. Looking into it but you'll know how to do that faster I believe..

### CODE REVIEW

**Comment by ebridges** [comment]
Thanks I'll push a new version as soon as i merge #9

**Comment by ebridges** [comment]
@jcrben thanks again for the interest in the project!  Just out of curiosity, can you provide more info on where/how it's being used (I'm not familiar with freenode)?  I'm happy that this is being seen as useful outside of my own personal finances, and would love to hear how it's helping others.

**Comment by jcrben** [comment]
We're using it to populate entries in https://hledger.org

Freenode is an IRC server https://en.m.wikipedia.org/wiki/Freenode. Lots of clients out there but http://webchat.freenode.net/?channels=hledger&randomnick=1 should get you into the channel.

**Comment by simonmichael** [comment]
@ebridges, I've just started using it (inspired by @jcrben in the #hledger chat channel), first to try out Plaid and now as my preferred way to download daily bank transactions as CSV, to import into hledger
(using rules like [these](https://gist.github.com/simonmichael/b841ba89aaf3520458ec3a1950c80436)). 

Previously I was using Tiller, which uses Yodlee. plaid2qif's current CSV output is much more basic. I see more data is available, but unfortunately not the full description - Plaid seems to truncate it. I now have plaid credentials stored in plain text on my file system, also. But querying Plaid directly avoids storing financial data with google, Tiller's fee, more importantly their polling delay, and allows me to see pending transactions.

I had trouble getting started, and might have switched to plaid2text if that had installed cleanly. But it's getting the job done now. Thanks!

**Comment by ebridges** [comment]
@simonmichael sorry for the looooong delay replying LoL.  Sounds great, and I'm glad that you have found this project useful.  If you have any suggestions for ways to improve it or make it otherwise more useful, please feel free to open tickets with your ideas.  Thanks!

**Pull request merged**
